name: Gitleaks
description: Run Gitleaks on Push and PR events
branding:
  color: purple
  icon: eye
inputs:
  append-repo-config:
    description: 'Append the provided or default config with the repo config, Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.github/.gitleaks.toml'
  config-path:
    description: 'Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.github/.gitleaks.toml'
outputs:
  result: # id of output
    description: 'Gitleaks log output'
  exitcode: # id of output
    description: 'Success for failure value from scan'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.append-repo-config }}
    - ${{ inputs.config-path }}
